language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install

script: ./vendor/bin/phpunit

git:
  depth: 5
