language: php

php:
  - 5.6
  - 7.0
  - 7.2
  - 7.3

before_script:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install

script: ./vendor/bin/phpunit

git:
  depth: 5
