language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  - composer self-update
  - composer install

script: ./vendor/bin/phpunit

git:
  depth: 5
